"""Agent 3 — chart note drafting.

    draft_note(...)             -> old stub: string-template note assembly
    draft_note_with_claude(...) -> real implementation: Claude Haiku tool-use
    call, drafting a SOAP note plus a clinician action-items checklist from
    the transcript, the triage decision already made (by Agent 2), and the
    patient's FHIR context.

Split into its own file, separate from Agent 2 (services/triage_service.py),
so each agent's model choice, system prompt, and reasoning logic stays
independently readable/editable/testable — this file only knows about
note-drafting, not triage.

Both this file and triage_service.py share FHIR dataset access via
services/fhir_context.py (load_fhir_record / build_fhir_context_block /
format_transcript / API_URL / API_VERSION) rather than each re-implementing
FHIR parsing — that logic lives in exactly one place for both agents.
"""
from __future__ import annotations

from typing import Any

import requests

from config import Config
from services.fhir_context import (
    API_URL,
    API_VERSION,
    build_fhir_context_block,
    format_transcript,
    load_fhir_record,
)

# ---------------------------------------------------------------------------
# Old string-template stub (kept as fallback/reference, not used by the real
# path). Moved here from triage_service.py — this is where it always
# logically belonged, it just hadn't been split out yet.
# ---------------------------------------------------------------------------
def draft_note(patient: dict, encounter: dict, result: dict) -> str:
    """Agent 3 (old stub): assemble a chart note from context + disposition."""
    flags_text = (
        ", ".join(f'"{f}"' for f in result["flags"])
        if result["flags"]
        else "none reported"
    )
    gender_abbr = "F" if patient["gender"] == "female" else "M"
    rationale = "\n".join("- " + r for r in result["rationale"])
    return (
        "POST-DISCHARGE CHECK-IN NOTE\n"
        f"Patient: {patient['name']}, {patient['age']}{gender_abbr}\n"
        f"Days since discharge: {encounter['daysSinceDischarge']}\n"
        f"Discharge context: {encounter['dischargeDx']}\n\n"
        "Subjective: Patient reached by phone for scheduled post-discharge "
        "check-in.\n"
        f"Key statements flagged during call: {flags_text}.\n\n"
        f"Assessment: {result['label']}.\n"
        f"{rationale}\n\n"
        f"Plan: {result['label']} — see disposition above. Care team notified "
        "via queue.\n\n"
        "⚠️ This note was generated by rule-based demo logic, not a "
        "clinician-reviewed LLM output. Not for real clinical use."
    )


# ---------------------------------------------------------------------------
# Real Agent 3 — Claude-based chart note drafting
# ---------------------------------------------------------------------------
NOTE_MODEL = "claude-haiku-4-5"  # drafting/formatting, not the reasoning-heavy step

NOTE_SYSTEM_PROMPT = (
    "You draft concise post-discharge check-in chart notes for a clinician to "
    "review and finalize directly in Epic. Use clinical shorthand, not prose "
    "padding — this is copied into the chart as-is after clinician sign-off.\n\n"
    "Write a standard SOAP-style note:\n"
    "- Subjective: what the patient/family reported on this call. Ground this "
    "only in the transcript provided — do not add symptoms or statements that "
    "were not actually said.\n"
    "- Assessment: the triage disposition already decided and the clinical "
    "reasoning behind it, informed by the patient's known conditions, "
    "medications, and recent results (not just today's call in isolation).\n"
    "- Plan: the disposition already decided (do not re-decide or contradict "
    "it) plus any condition-specific follow-up guidance worth noting for the "
    "patient.\n\n"
    "Separately, produce a short action_items checklist: 2-5 concrete, "
    "imperative next steps for the clinician or care team (e.g. \"Order BMP\", "
    "\"Schedule GI follow-up within 1 week\", \"Call patient directly — "
    "insufficient information obtained on this check-in\"). Action items must "
    "follow directly from the disposition and rationale already decided — do "
    "not introduce a new clinical claim or change the disposition here.\n\n"
    "Only reference clinical specifics (medications, conditions, prior "
    "results) that actually appear in the clinical context you were given — "
    "never invent one to sound more specific.\n\n"
    "This is an AI-drafted note. A clinician reviews and finalizes it before "
    "anything is entered in the chart — never state or imply it has already "
    "been clinically reviewed or finalized."
)

NOTE_TOOL = {
    "name": "record_chart_note",
    "description": "Record the drafted post-discharge check-in chart note",
    "input_schema": {
        "type": "object",
        "required": ["subjective", "assessment", "plan", "action_items"],
        "properties": {
            "subjective": {"type": "string"},
            "assessment": {"type": "string"},
            "plan": {"type": "string"},
            "action_items": {
                "type": "array",
                "items": {"type": "string"},
                "description": (
                    "2-5 short imperative next steps for the clinician/care "
                    "team, consistent with the disposition and rationale "
                    "already decided — not a re-triage."
                ),
            },
        },
    },
}


def draft_note_with_claude(
    transcript: list[list[str]], patient: dict, encounter: dict, result: dict
) -> str:
    """Agent 3 (real): Claude Haiku tool-use call drafting a SOAP note plus a
    clinician action-items checklist, formatted as a single string ready to
    paste into Epic. Reuses the same FHIR context Agent 2 builds so the note
    can cite real problem-list/medication specifics, not just what was said
    on the call.

    Returns a plain string — same return type as draft_note() above — so
    callers (routes/tool.py, services/call_service.py) and
    models.TriageResult.note (a Text column) need no shape changes.
    """
    if not Config.ANTHROPIC_API_KEY:
        raise RuntimeError("ANTHROPIC_API_KEY is not set — check your .env file.")

    patient_context, encounter_fhir = load_fhir_record(patient["id"])
    fhir_block = build_fhir_context_block(patient_context, encounter_fhir)

    rationale_text = "\n".join(f"- {r}" for r in result.get("rationale", []))
    user_message = (
        f"Patient clinical context:\n{fhir_block}\n\n"
        f"Check-in transcript:\n{format_transcript(transcript)}\n\n"
        f"Triage decision already made: {result['severity']} — {result['label']}\n"
        f"Rationale:\n{rationale_text}\n\n"
        "Draft the chart note using the record_chart_note tool."
    )

    resp = requests.post(
        API_URL,
        headers={
            "x-api-key": Config.ANTHROPIC_API_KEY,
            "anthropic-version": API_VERSION,
            "content-type": "application/json",
        },
        json={
            "model": NOTE_MODEL,
            "max_tokens": 768,
            "system": NOTE_SYSTEM_PROMPT,
            "tools": [NOTE_TOOL],
            "tool_choice": {"type": "tool", "name": "record_chart_note"},
            "messages": [{"role": "user", "content": user_message}],
        },
        timeout=60,
    )
    resp.raise_for_status()
    data = resp.json()
    tool_block = next(b for b in data["content"] if b["type"] == "tool_use")
    note = tool_block["input"]

    gender_abbr = "F" if patient.get("gender") == "female" else "M"
    action_items_text = (
        "\n".join(f"[ ] {a}" for a in note.get("action_items", [])) or "(none)"
    )
    return (
        "POST-DISCHARGE CHECK-IN NOTE\n"
        f"Patient: {patient.get('name', patient.get('id', 'unknown'))}, "
        f"{patient.get('age', '?')}{gender_abbr}\n"
        f"Days since discharge: {encounter.get('daysSinceDischarge', '?')}\n"
        f"Discharge context: {encounter.get('dischargeDx', '?')}\n\n"
        f"Subjective: {note['subjective']}\n\n"
        f"Assessment: {note['assessment']}\n\n"
        f"Plan: {note['plan']}\n\n"
        "ACTION ITEMS (clinician to finalize):\n"
        f"{action_items_text}\n\n"
        "⚠️ AI-drafted from a check-in call — clinician review "
        "required before this is entered in the chart."
    )
